music_directory    "~/Music/kodydeda/Music/Library/"
playlist_directory "~/Music/kodydeda/Music/rcmp/playlist"
db_file            "~/.config/mpd/database"
log_file           "~/.config/mpd/mpd.log"
bind_to_address    "127.0.0.1"
port               "6600"
auto_update        "yes"
audio_output {
    type        "osx"
    name        "CoreAudio"
    mixer_type  "software"
}
