unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -g prefix C-a

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g mouse on

set-window-option -g mode-keys vi

# split
bind-key -n C-e split-window -h
bind-key -n C-v split-window -v

# allow vim-tmux-navigator to pass C-l through for clearing (optional)
# vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"
bind-key -n C-\\ if-shell "$is_vim" "send-keys C-\\" "select-pane -l"

# [sessions]
bind -n M-h switch-client -p
bind -n M-l switch-client -n

# [pane] resize
bind-key -n C-S-h resize-pane -L 5
bind-key -n C-S-j resize-pane -D 5
bind-key -n C-S-k resize-pane -U 5
bind-key -n C-S-l resize-pane -R 5
bind-key -n C-w kill-pane

# [tab]
bind-key -n M-t new-window
# bind-key -n M-l next-window
# bind-key -n M-h previous-window
bind-key -n M-w kill-window

# [tab] focus
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

set-option -g status-position bottom

if-shell "defaults read -g AppleInterfaceStyle 2>/dev/null | grep -q Dark" \
  "set -g @catppuccin_flavor 'mocha'" \
  "set -g @catppuccin_flavor 'latte'"
set -g @catppuccin_window_status_style "rounded"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.0'

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

set -g status-style bg=default
